# /etc/nginx/nginx.conf (Este archivo DEBE ser copiado en la Etapa 2 del Dockerfile)

# 1. Quitamos la directiva 'user' o la ponemos a 'appuser' si es necesaria.
# user appuser; 

worker_processes auto;

# 2. ¡La Solución para el Permiso Denegado!
# Movemos el archivo PID a /tmp, donde cualquier usuario puede escribir.
pid /tmp/nginx.pid; 

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name localhost;

        root /usr/share/nginx/html;
        index index.html;

        # Configuración para que las rutas de la PWA funcionen (enrutamiento de lado del cliente)
        location / {
            try_files $uri $uri/ /index.html;
        }

        # Configuración para servir el archivo JS con la URL de la API
        location = /config.js {
            default_type application/javascript;
        }
    }
}