name: "Revisar Titulos de Pull Request"
on:
  pull_request:
    types: [opened, edited]
jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Revisar titulo
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          if [[ ! "$PR_TITLE" =~ ^(feat|fix|docs|chore|refactor|test)\(.*\):\ .+$ ]]; then
            echo "❌ El titulo del PR no sigue el formato de Conventional Commits : 'type(scope): description'."
            echo "Tipos permitidos: feat, fix, docs, chore, refactor, test."
            exit 1
          fi